services:
  postgres:
    image: 'postgres:13'
    container_name: 'java-postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=mypassword'
      - 'POSTGRES_DB=task-db'