server:
  port: 8081

spring:
  application:
    name: NoteService
  datasource:
    url: jdbc:postgresql://localhost:5432/task-db
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
